# Dockerfile
# RabbitMQ

# How big is image? > docker images

version: "3.2"
services:
  dl:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - docker.env
    depends_on:
      - rabbitmq
    ports:
     - 8080:8080
    volumes:
     - D:\Files\Media:/data/local

  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq